services:
  cadddy: 
    image: caddy:latest
    container_name: sym-reverse-proxy
    hostname: sym-reverse-proxy
    profiles: ["profiles", "all"]
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      #- caddy_data:/data
      #- caddy_config:/config
    restart: unless-stopped
