services:
  dozzle:
    image: amir20/dozzle:latest
    hostname: dozzle
    container_name: dozzle
    profiles: ["dozzle", "all"]
    networks: 
      - sym-backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - sym-dozzle:/data
    restart: unless-stopped
volumes:
  sym-dozzle:
