# ref: https://github.com/minio/minio/blob/master/docs/orchestration/docker-compose/docker-compose.yaml
services:
  minio:
    image: ${MINIO_IMAGE:-docker.io/bitnami/minio:2025.3.12}
    container_name: sym-minio
    hostname: sym-minio
    profiles: ["minio", "all"]
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS}
    volumes:
      - minio_data:/data
    ports:
      - "9000"
      - "9001"
    networks:
      - sym-backend
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  minio_data:
    driver: local
